### ISSUE TITLE
Poids de la homepage

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/archifiltre-site-v2#164]
Au chargement de la homepage

<img width="709" alt="Capture d’écran 2024-01-26 à 15 26 44" src="https://github.com/SocialGouv/archifiltre-site-v2/assets/124937/245b7723-32fd-49e7-8eea-51a68a8aa069">

**Comment by sam-pires** [comment]
Suite à la refonte du site sur un nouveau CMS, le sujet n'est plus d'actualité, je ferme l'issue
